name = "yam-todo"
compatibility_date = "2024-05-28"
pages_build_output_dir = "./.vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL="https://cqlqfxlpveahyptvvled.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxbHFmeGxwdmVhaHlwdHZ2bGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjEyNDIsImV4cCI6MjA2Mzk5NzI0Mn0.CK7QTAy6CjwTiZ_dl1oAO487XBD5pGfczu50534oC-Y"

[[d1_databases]]
binding = "DB"
database_name = "yam-todo"
database_id = "9b952670-8c8e-4baa-8bd1-162da4241ebc"
