name = "yam-todo"
compatibility_date = "2024-05-28"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "yam-todo"
database_id = "9b952670-8c8e-4baa-8bd1-162da4241ebc"
